PolymathNetwork/Polymesh

- scripts/cli/index.js
Update to binary keys in scripts
> Update to binary keys in scripts

- polymesh_schema.json
- runtime/src/asset.rs
- runtime/src/constants.rs
- runtime/src/dividend.rs
- runtime/src/general_tm.rs
- runtime/src/simple_token.rs
- runtime/src/voting.rs
Total supply limited to 1 trillion (10^12) and decimal precision set to 10^6. 
This gives a net max total units = 10^18.
TODO:
> Total supply and decimal precision changes

- Cargo.toml
- src/chain_spec.rs
Hey, I was looking through your blockchain, looks great saw some things I just did for the substrate blockchain I was building and thought Id contribute. I added a token name and decimal (guessed the values in the config file). There is a bunch more I can do by the way, like set up telemetry in the chainspec, by default make nodes spin up off a chianspec.....which due to WASM's non deterministic compilation would make it hard to connect separate nodes not on the same machine if not done of a pre compiled chainspec.
> added token decimals and token name to chainspec

- runtime/src/constants.rs
- runtime/src/impls.rs
https://github.com/PolymathNetwork/Polymesh/pull/121 and https://github.com/PolymathNetwork/Polymesh/pull/131 changed poly decimals to 6. This PR updates fees and constants accordingly.
> Updated fees

- Cargo.lock
- polymesh_schema.json
- runtime/src/voting.rs
`proposal` is reserved by polkadot-js. It represents an extrinsic call.
> Renamed voting proposal to motion

- polymesh_schema.json
Remon found this duplicated type in our schema.
> Remove duplicated type

- polymesh_schema.json
- primitives/src/authorization.rs
- primitives/src/lib.rs
- runtime/src/asset.rs
- runtime/src/balances.rs
- runtime/src/dividend.rs
- runtime/src/general_tm.rs
- runtime/src/identity.rs
- runtime/src/mips.rs
- runtime/src/percentage_tm.rs
- runtime/src/runtime.rs
- runtime/src/staking.rs
- runtime/src/test/identity.rs
- runtime/src/test/storage.rs
- runtime/src/voting.rs
I probably should have split this in two PRs with generic stuff in one and ticker transfer specific in the other but here we are :)
> [MESH-527] Ticker transfer based on generic authorization 

- runtime/src/asset.rs
- runtime/src/batch_dispatch_info.rs
- runtime/src/general_tm.rs
- runtime/src/group.rs
- runtime/src/identity.rs
- runtime/src/lib.rs
- runtime/src/mips.rs
- runtime/src/test/identity.rs
```
#[weight = BatchDispatchInfo::new_normal(3_000, 10_000)]
fn bulk_op(origin, id: Identity, items: Vec<_>) -> Result {
...
}
```
> Mesh 558/remove claim issuer

- pallets/common/src/traits/identity.rs
- pallets/identity/src/lib.rs
- pallets/runtime/src/committee.rs
- pallets/runtime/src/dividend.rs
- pallets/runtime/src/general_tm.rs
- pallets/runtime/src/mips.rs
- pallets/runtime/src/runtime.rs
- pallets/runtime/src/test/storage.rs
- pallets/runtime/src/voting.rs
- src/chain_spec.rs
`KYCServiceProviders` shows as `kYCServiceProviders`
> Rename KYCServiceProviders as KycServiceProviders

- pallets/runtime/src/simple_token.rs
> Mesh-644 Simple Token tests

- pallets/runtime/src/multisig.rs
- pallets/runtime/src/test/multisig.rs
This is a quick fix for the previous merge commit problem. In case we don't merge #192 first where this fix originates from.
> multisig test fix

- pallets/runtime/src/bridge.rs
- pallets/runtime/src/test/bridge.rs
- pallets/runtime/src/test/multisig.rs
> Mesh 750: bridge admin key

- polymesh_schema.json
> Missing `InactiveMember` type

- pallets/runtime/src/bridge.rs
- pallets/runtime/src/test/bridge.rs
- src/chain_spec.rs
Sets Alice as the bridge admin in `testnet_genesis`
Allows the bridge controller to submit `handle_bridge_tx` calls
> MESH-834/Make the bridge easier to test

- .github/workflows/main.yml
When a dev merges changes to develop that include changes to the polymesh_schema.json it will commit back the changes to the polymesh_issuer dApp
> Polymesh Schema updates

- polymesh_schema.json
- scripts/cli/util/init.js
Also hoisted some nested struct definitions because they don't play nice with polkadot
> fix: separate types from RPC definitions

- pallets/asset/rpc/runtime-api/src/lib.rs
It's just a documentation fix.
> Documentation fixed

- pallets/asset/src/lib.rs
- pallets/runtime/develop/src/runtime.rs
- pallets/runtime/testnet-v1/src/runtime.rs
Return insufficient balance error if there's insufficient balance.
> Updated can transfer

- pallets/committee/src/lib.rs
- src/chain_spec.rs
Sample code to extract GC mermber votes:
```
api.query.system.events(async (events) => {
events.forEach(async (record) => {
const { event, phase } = record;
if (event.section == "polymeshCommittee" && event.method == "Voted") {
let proposal_hash = event.data[2];
let proposal = JSON.parse(await api.query.polymeshCommittee.proposalOf(proposal_hash));
let topic;
let vote;
// Hardcoded here but there's probably a way to resolve this into proper name.
// Polkadot UI resolves it.
if (proposal["callIndex"] == 0x140e) {
topic = " enacting referendum id ";
} else if (proposal["callIndex"] == 0x140f) {
topic = " rejecting referendum id ";
}
if (event.data[4] == 1) {
console.log(event.data[4]);
vote = "for";
} else {
vote = "against";
}
console.log(event.data[2] + " voted " + vote + topic + …
```
> Added more events

- pallets/committee/src/lib.rs
- pallets/runtime/common/src/bridge.rs
Fixes some events which don't fire when executed through governance, and added some useful events to the bridge.
> MESH-989: Fix events

- pallets/runtime/develop/src/runtime.rs
- pallets/runtime/testnet-v1/src/runtime.rs
Fix SlashDeferDuration duration
> Chain spec fixes

- pallets/runtime/develop/src/fee_details.rs
- pallets/runtime/testnet-v1/src/fee_details.rs
- src/chain_spec.rs
- fix mismatch between operator / sentry key pairs in genesis
- improve develop chain pip timeline for testing
- add correct payer for bridge relayers w/ batch transactions
> Misc. fixes

- pallets/runtime/develop/src/runtime.rs
- pallets/runtime/testnet-v1/src/runtime.rs
- src/chain_spec.rs
Remove fee multiplier as it is too extreme with Aldebaran fees
Adjust bridge limit from 25k to 30k
> Fix fees and adjust bridge limit

- polymesh_schema.json
This will allow us to use `develop` branch on app.polymesh.live
> Updated schema

- src/chain_spec.rs
- src/command.rs
- src/service.rs
Update to V2 testnet
- includes some config tweaks to correctly fund accounts
> Update to V2 testnet

- pallets/compliance-manager/src/lib.rs
Drive-by from review of https://github.com/PolymathNetwork/Polymesh/pull/534.
> Simplify `get_latest_rule_id`

- pallets/common/src/lib.rs
- pallets/identity/src/lib.rs
- pallets/pips/src/lib.rs
- pallets/runtime/tests/src/identity_test.rs
Misc refactorings on the identity pallet and some potential performance improvements (e..g, allocating less).
(Drive-by work from MESH-1213.)
Be sure to review with whitespace changes ignored.
> Misc cleanup of identity, etc.

- Cargo.lock
- pallets/runtime/develop/src/runtime.rs
- pallets/runtime/testnet-v1/src/runtime.rs
Regenerate chain spec files for genesis.
> Regenerate chain specs

- Cargo.lock
- pallets/asset/src/lib.rs
- pallets/runtime/tests/src/ext_builder.rs
- polymesh_schema.json
- src/chain_spec.rs
Based on https://github.com/PolymathNetwork/Polymesh/pull/544 (MESH-1222).
> MESH-1223: Reserve Classic tickers to systematic DID on genesis

- .circleci/config.yml
- pallets/asset/src/lib.rs
- pallets/compliance-manager/src/lib.rs
- pallets/runtime/tests/src/asset_test.rs
- pallets/runtime/tests/src/compliance_manager_test.rs
- pallets/runtime/tests/src/confidential_test.rs
- pallets/runtime/tests/src/ext_builder.rs
- pallets/runtime/tests/src/storage.rs
Resets CircleCI cache and adds cryptography repo to lint job so that it completes fully.
Also fixed the existing lint issues.
> Reset CircleCI cache

- Cargo.lock
- pallets/asset/Cargo.toml
- pallets/asset/src/lib.rs
- pallets/common/src/protocol_fee.rs
- pallets/identity/src/lib.rs
- pallets/protocol-fee/src/lib.rs
- pallets/runtime/develop/src/runtime.rs
- pallets/runtime/testnet-v1/src/runtime.rs
- pallets/runtime/tests/src/asset_test.rs
- pallets/runtime/tests/src/protocol_fee.rs
Based on https://github.com/PolymathNetwork/Polymesh/pull/547.
> MESH-1227: Waive `ProtocolOp::AssetCreateAsset` if `classic_ticker.is_created`

- pallets/common/src/traits/transaction_payment.rs
- pallets/identity/src/lib.rs
- pallets/runtime/develop/src/fee_details.rs
- pallets/runtime/develop/src/lib.rs
- pallets/runtime/testnet-v1/src/fee_details.rs
- pallets/runtime/testnet-v1/src/lib.rs
- pallets/runtime/tests/src/cdd_offchain_worker/mock.rs
- pallets/runtime/tests/src/fee_details.rs
- pallets/runtime/tests/src/identity_test.rs
- pallets/runtime/tests/src/staking/mock.rs
- pallets/runtime/tests/src/storage.rs
- pallets/transaction-payment/src/lib.rs
Also do some code cleanup & refactoring.
> MESH-1216: `get_valid_payer`: only accept `AccountId`.

- Cargo.lock
- pallets/confidential-asset/Cargo.toml
- pallets/confidential-asset/src/lib.rs
- pallets/runtime/tests/Cargo.toml
- pallets/runtime/tests/src/confidential_asset_test.rs
- pallets/runtime/tests/src/lib.rs
- pallets/runtime/tests/src/storage.rs
Addresses CRYP-159
Modified version of https://github.com/PolymathNetwork/Polymesh/pull/520 based on the discussions in https://polymath.atlassian.net/wiki/spaces/CE/pages/664403973/Data+structures+and+their+placement
Related PR: https://github.com/PolymathNetwork/cryptography/pull/80
> Integrate mercat account

- pallets/runtime/develop/src/runtime.rs
- pallets/runtime/testnet/src/runtime.rs
- pallets/staking/src/lib.rs
Update max_inflation from 20% to 14%
Update reward claim weights
> Alcyone 2.0.2

- pallets/identity/src/lib.rs
- pallets/portfolio/src/lib.rs
- pallets/runtime/tests/src/portfolio.rs
- polymesh_schema.json
- Cache portfolios in the custody of a did
- Fix schema
- Add a wrapper function for mock cdd
> [Tooling] Backporting features and fixes

- .circleci/config.yml
Switch circleci configuration to use versioned polymath-provided rust
containers.
> DEVOPS-116 - use Polymath's Rust container

- Cargo.lock
- Cargo.toml
- pallets/asset/src/lib.rs
- pallets/common/src/traits/identity.rs
- pallets/corporate-actions/Cargo.toml
- pallets/corporate-actions/src/lib.rs
- pallets/identity/src/lib.rs
- pallets/runtime/develop/Cargo.toml
- pallets/runtime/develop/src/runtime.rs
- pallets/runtime/testnet/Cargo.toml
- pallets/runtime/testnet/src/runtime.rs
- pallets/runtime/tests/Cargo.toml
- pallets/runtime/tests/src/corporate_actions_test.rs
- pallets/runtime/tests/src/lib.rs
- pallets/runtime/tests/src/pips_test.rs
- pallets/runtime/tests/src/portfolio.rs
- pallets/runtime/tests/src/staking/mock.rs
- pallets/runtime/tests/src/storage.rs
- pallets/weights/Cargo.toml
- pallets/weights/src/lib.rs
- pallets/weights/src/pallet_corporate_actions.rs
- polymesh_schema.json
- primitives/src/authorization.rs
Also:
- Simplify `find_ceiling` + other drive-by refactoring.
> MESH-1097: Configure Corporate Actions for an asset

- pallets/asset/src/lib.rs
- pallets/corporate-actions/src/lib.rs
- pallets/runtime/tests/src/corporate_actions_test.rs
- pallets/weights/src/pallet_corporate_actions.rs
- polymesh_schema.json
Based atop https://github.com/PolymathNetwork/Polymesh/pull/673.
This PR's changes start from https://github.com/PolymathNetwork/Polymesh/pull/678/commits/b0b02327ca134c74913040d157d5c9959ca9f720.
> MESH-1269: Initiating a Corporate Action

- Cargo.lock
- bin/executor/Cargo.toml
This should fix the Cargo.lock bug @Centril
> Use local im-online pallet in node-executor

- pallets/identity/src/lib.rs
- primitives/src/cdd_id.rs
- primitives/src/identity_id.rs
Fix migration code and remove bit masking.
> Migration fix for `tooling` branch

- Cargo.lock
- pallets/confidential-asset/src/lib.rs
- pallets/runtime/tests/src/confidential_asset_test.rs
- pallets/runtime/tests/src/settlement_test.rs
- pallets/settlement/src/lib.rs
- polymesh_schema.json
- primitives/Cargo.toml
- primitives/src/asset.rs
- primitives/src/lib.rs
- scripts/cli/tests/0_create_identities.js
- scripts/cli/tests/12_A_settlement.js
- scripts/cli/tests/12_B_settlement.js
- scripts/cli/tests/2_key_management.js
- scripts/cli/tests/4_permission_management.js
Added base64 to binary types that were causing troubles during my end-to-end test of confidential transfer.
> Cryp 169/end to end test

- pallets/compliance-manager/src/lib.rs
- pallets/settlement/src/lib.rs
Settlement fixes are backported from @vkomenda 's PR.
> Fixed settlement and cm migration

- pallets/asset/src/checkpoint.rs
- pallets/runtime/tests/src/asset_test.rs
- pallets/runtime/tests/src/corporate_actions_test.rs
- primitives/src/calendar.rs
Resolves https://github.com/PolymathNetwork/Polymesh/pull/692#discussion_r512436564.
Review this with whitespace changes hidden.
> MESH-1353: use millisecs in storage + inputs for checkpoints

- pallets/asset/src/checkpoint.rs
Resolves https://github.com/PolymathNetwork/Polymesh/pull/692#discussion_r512434744.
> MESH-1352: Create intermediate CPs for untriggered schedules

- pallets/confidential-asset/src/lib.rs
- pallets/settlement/src/lib.rs
> [MERCAT]: Add pallet docs

- pallets/asset/src/checkpoint.rs
- pallets/common/src/protocol_fee.rs
- pallets/corporate-actions/src/ballot.rs
- pallets/corporate-actions/src/lib.rs
- pallets/runtime/develop/src/runtime.rs
- pallets/runtime/testnet/src/runtime.rs
- pallets/runtime/tests/src/corporate_actions_test.rs
- pallets/runtime/tests/src/storage.rs
- polymesh_schema.json
Based on https://github.com/PolymathNetwork/Polymesh/pull/692.
Will add tests in a different PR.
> MESH-1272: Implement Corporate Ballots

- pallets/asset/src/checkpoint.rs
- pallets/corporate-actions/src/ballot.rs
- pallets/corporate-actions/src/distribution.rs
- pallets/corporate-actions/src/lib.rs
- pallets/runtime/common/src/dividend.rs
- pallets/weights/src/pallet_corporate_actions.rs
Based on https://github.com/PolymathNetwork/Polymesh/pull/716.
Tests will be added in a follow-up PR.
> MESH-1348 + MESH-1347: Remove CA + Changing record dates

- pallets/portfolio/src/lib.rs
The unrestricted portfolio permission was redundant since the extrinsic was already covered with the extrinsic permission.
> Removed a redundant permission

- pallets/asset/src/checkpoint.rs
- pallets/asset/src/lib.rs
- pallets/bridge/src/lib.rs
- pallets/identity/src/lib.rs
- pallets/portfolio/src/lib.rs
- pallets/runtime/develop/src/constants.rs
- pallets/runtime/develop/src/fee_details.rs
- pallets/runtime/testnet/src/fee_details.rs
- pallets/runtime/tests/src/asset_test.rs
- pallets/staking/src/lib.rs
- polymesh_schema.json
- primitives/src/calendar.rs
- src/chain_spec.rs
Adds:
Changed validator count to accommodate genesis authorities (#764)
CalendarPeriod: fix schema (#761)
Add batches to the bridge module (#767)
Renaming and minor fixes (#760)
Removed redundant permission (#758)
> 2.3 updates

- pallets/pips/src/lib.rs
- pallets/runtime/tests/src/ext_builder.rs
- pallets/runtime/tests/src/pips_test.rs
- polymesh_schema.json
- scripts/cli/tests/11_governance_management.js
- src/chain_spec.rs
Resolves https://polymath.atlassian.net/browse/MESH-1393.
Also nixes cool-off period.
> MESH-1393: Refactor snapshots using live queue model

- pallets/asset/src/benchmarking.rs
- pallets/confidential/Cargo.toml
- pallets/confidential/src/benchmarking.rs
- pallets/confidential/src/lib.rs
- pallets/identity/Cargo.toml
- pallets/identity/src/benchmarking.rs
- pallets/runtime/develop/Cargo.toml
- pallets/runtime/develop/src/runtime.rs
- pallets/runtime/tests/src/storage.rs
- pallets/weights/Cargo.toml
- pallets/weights/src/lib.rs
- pallets/weights/src/pallet_confidential.rs
Confidential pallet is only a kind of integration test with Cryptography library and this PR is just to setup the benchmark framework on this. It measures the only 2 extrinsics from this pallet.
Pls note that Confidential pallet is used only in Dev.
> Add benchmarks to Confidential

- Cargo.lock
- pallets/asset/src/lib.rs
- pallets/balances/src/lib.rs
- pallets/bridge/src/lib.rs
- pallets/committee/src/lib.rs
- pallets/compliance-manager/src/lib.rs
- pallets/contracts/src/lib.rs
- pallets/corporate-actions/src/distribution.rs
- pallets/corporate-actions/src/lib.rs
- pallets/identity/src/lib.rs
- pallets/im-online/src/lib.rs
- pallets/protocol-fee/src/lib.rs
- pallets/runtime/common/src/sto_capped.rs
- pallets/runtime/tests/src/staking/mod.rs
- pallets/settlement/src/lib.rs
- pallets/staking/src/lib.rs
- pallets/sto/src/lib.rs
Resolves https://polymath.atlassian.net/browse/MESH-1366.
> MESH-1366: Nix unused error variants

- .circleci/config.yml
- Cargo.lock
- pallets/common/src/constants.rs
- pallets/contracts/src/benchmarking.rs
- pallets/identity/Cargo.toml
- pallets/identity/src/benchmarking.rs
- pallets/pips/src/benchmarking.rs
- pallets/runtime/develop/src/runtime.rs
- pallets/runtime/testnet/src/runtime.rs
- pallets/settlement/src/benchmarking.rs
- pallets/settlement/src/lib.rs
- polymesh_schema.json
- rpc/runtime-api/src/pips.rs
- Cleaned up references to referendums
- Fixed a hex counting error in error codes
- Added benchmark binary build to CI
- Removed daily build on `master` branch
- Cleaned up compiler warnings in benchmarks
> Minor fixes and added benchmarks build to CI

- pallets/confidential-asset/Cargo.toml
- pallets/confidential-asset/src/lib.rs
- pallets/confidential/Cargo.toml
- pallets/confidential/src/lib.rs
- pallets/runtime/develop/Cargo.toml
- pallets/runtime/testnet/Cargo.toml
- pallets/runtime/tests/Cargo.toml
- pallets/runtime/tests/src/confidential_asset_test.rs
- pallets/runtime/tests/src/settlement_test.rs
- pallets/runtime/tests/src/transaction_ordering_test.rs
- pallets/settlement/Cargo.toml
- primitives/Cargo.toml
- primitives/src/investor_zkproof_data.rs
- primitives/src/valid_proof_of_investor.rs
Some work is done inside cryptography lib (branch `CRYP-187/change-mercat-dependencies_miguel`), and some fixes are here.
> Fix Crypto dependencies

- pallets/runtime/testnet/src/runtime.rs
As per https://github.com/PolymathNetwork/Polymesh/blob/v2.2.0/pallets/runtime/testnet/src/runtime.rs#L106
> Fix testnet authoring_version

- pallets/asset/src/checkpoint.rs
- pallets/asset/src/lib.rs
- pallets/bridge/src/lib.rs
- pallets/committee/src/lib.rs
- pallets/confidential/src/lib.rs
- pallets/corporate-actions/src/ballot.rs
- pallets/corporate-actions/src/lib.rs
- pallets/identity/src/lib.rs
- pallets/multisig/src/lib.rs
- pallets/portfolio/src/lib.rs
- pallets/runtime/tests/src/corporate_actions_test.rs
- pallets/sto/src/lib.rs
(It should not be part of 2.4 release as it will require a storage migration otherwise)
> Mesh 1400/update storage hashers

- pallets/identity/src/lib.rs
- pallets/identity/src/migration.rs
- pallets/runtime/develop/src/runtime.rs
> Use mocked InvestorUid from crypto

- Cargo.lock
- pallets/asset/src/lib.rs
- pallets/common/src/traits/asset.rs
- pallets/common/src/traits/mod.rs
- pallets/identity/src/lib.rs
- pallets/runtime/tests/src/staking/mock.rs
- Removal of IU claim is only allowed when the target ScopeId has 0 balance.
> MESH-1409/Add check for zero balance during revoke of IU claim

- Cargo.lock
- scripts/cli/package.json
- scripts/cli/tests/10_bridge_transfer.js
- modified 10_bridge_transfer script
- modified package.json
> bridge transfer script fix

- pallets/bridge/src/lib.rs
- pallets/common/src/constants.rs
- pallets/common/src/traits/identity.rs
- pallets/identity/src/lib.rs
- pallets/multisig/src/lib.rs
- pallets/pips/src/lib.rs
- pallets/runtime/develop/src/runtime.rs
- pallets/runtime/testnet/src/runtime.rs
- pallets/runtime/tests/src/bridge.rs
- pallets/runtime/tests/src/multisig.rs
- pallets/runtime/tests/src/staking/mock.rs
- pallets/runtime/tests/src/storage.rs
- pallets/settlement/src/lib.rs
- scripts/test.sh
TODO: Update weights. Perhaps in `MESH-1294`.
> MESH-1294/delay multisig proposal execution

- Cargo.lock
- pallets/identity/Cargo.toml
- pallets/identity/src/lib.rs
- pallets/multisig/src/lib.rs
- pallets/permissions/src/lib.rs
- pallets/pips/src/lib.rs
- pallets/portfolio/src/lib.rs
- pallets/protocol-fee/src/lib.rs
* Contains various refactorings, simplications, but most importantly a reduction in unnecessary allocations.
- Check permissions in `Pips::{reschedule_execution, snapshot, clear_snapshot}`.
> Misc cleanups & refactorings, Part 2

- pallets/staking/src/lib.rs
- Slashing will happen even when slashing targets are set to None. However, the amount of slash will be zero in those cases.
> Re enable slashing

- Cargo.lock
- Cargo.toml
- bin/crypto-cli/Cargo.toml
- bin/crypto-cli/README.md
- bin/crypto-cli/src/main.rs
Very barebones helper tool to generate proofs for PUIS/Scope claims. Has a lot of scope (pun intended) for future improvements.
> Helper CLI

- .circleci/config.yml
- Cargo.lock
- pallets/runtime/develop/Cargo.toml
- pallets/runtime/testnet/Cargo.toml
- pallets/sudo/Cargo.toml
- pallets/sudo/README.md
- pallets/sudo/src/lib.rs
- pallets/sudo/src/mock.rs
- pallets/sudo/src/tests.rs
> MESH-1468/Add sudo pallet

- pallets/runtime/tests/src/asset_test.rs
- pallets/runtime/tests/src/contract_test.rs
This is best reviewed with whitespace changes hidden.
> MESH-1558: Simplify & harden contract tests

- pallets/identity/src/lib.rs
- pallets/runtime/mainnet/src/runtime.rs
- pallets/statistics/src/lib.rs
Reverts PolymathNetwork/Polymesh#925
Will add back later with storage migrations.
> Revert "MESH-1375: Fix module ordering + naming"

- pallets/runtime/develop/src/runtime.rs
- pallets/runtime/mainnet/src/constants.rs
- pallets/runtime/mainnet/src/runtime.rs
- pallets/runtime/testnet/src/runtime.rs
- pallets/settlement/src/lib.rs
- src/chain_spec.rs
These are internal test configs, not real mainnet configs.
> Update config params for mainnet

- pallets/asset/src/lib.rs
- pallets/balances/src/lib.rs
- pallets/base/src/lib.rs
- pallets/compliance-manager/src/lib.rs
- pallets/corporate-actions/src/lib.rs
- pallets/identity/src/lib.rs
- pallets/runtime/common/src/runtime.rs
- pallets/runtime/develop/src/runtime.rs
- pallets/runtime/itn/src/runtime.rs
- pallets/runtime/testnet/src/runtime.rs
- pallets/runtime/tests/src/asset_test.rs
- pallets/runtime/tests/src/storage.rs
- pallets/staking/src/lib.rs
- pallets/statistics/src/lib.rs
- More constants are now exposed via Metadata for easier consumption
> Expose constants in metadata

- pallets/runtime/tests/src/staking/mod.rs
- pallets/staking/src/lib.rs
> Fixed a bug preventing some operators from changing commission

- README.md
Adds details of the ITN to the project README.md file.
> Add ITN details to README

- pallets/identity/src/lib.rs
- pallets/runtime/tests/src/identity_test.rs
- Fix bug in primary key (PK) rotation where key already being attached to DID was allowed.
> Fix bug in primary key (PK) rotation

- pallets/external-agents/src/lib.rs
- polymesh_schema.json
- primitives/src/subset.rs
- Fixed bug in schema, `Meta` -> `ExceptMeta`
- Fixed bug in `fn agent_permissions` for `ExceptMeta`
> ExternalAgents: Fix schema + `fn agent_permissions`

- .circleci/config.yml
The integration test need to be compiled before the can run now.
> Fix CI integration test.

- pallets/common/src/traits/identity.rs
- pallets/identity/src/lib.rs
- scripts/cli/util/distributePOLYX.js
- `SecondaryKeyPermissionsUpdated` event now returns old and new perms
> MESH-1637/SecondaryKeyPermissionsUpdated event emits new permissions in both params

- Cargo.lock
- Cargo.toml
- pallets/common/src/traits/identity.rs
- pallets/identity/src/lib.rs
- pallets/runtime/develop/src/runtime.rs
- pallets/runtime/itn/src/runtime.rs
- pallets/runtime/testnet/src/runtime.rs
- pallets/runtime/tests/src/identity_test.rs
- primitives/src/identity.rs
- primitives/src/secondary_key.rs
Fixes for primary and secondary key duplicate linking.
Fix for SecondaryKeyPermissionsUpdated event parameters.
> Tooling 3.0.4

- pallets/portfolio/src/lib.rs
- pallets/runtime/tests/src/portfolio.rs
Part of https://polymath.atlassian.net/browse/MESH-1625.
- Adds `Portfolio.name_to_number` for fast `PortfolioName` => `PortfolioNumber` lookup.
> MESH-1625: Constant time portfolio name uniqueness

- pallets/corporate-actions/src/lib.rs
> Fix migrations in 3.1.0

- pallets/common/src/benchs/user.rs
- pallets/rewards/Cargo.toml
- pallets/rewards/src/benchmarking.rs
Fix for itn-rewards benchmarks.
> Itn rewards benchmarks fix

- Cargo.lock
- Cargo.toml
- pallets/identity/src/lib.rs
- pallets/runtime/develop/src/runtime.rs
- pallets/runtime/itn/src/runtime.rs
- pallets/runtime/testnet/src/runtime.rs
Ensure primary key rotation authorisation is issued by the identity whose primary key is being rotated.
> Fix Primary Key Rotation

- pallets/runtime/common/src/lib.rs
> Fix weight typo

- pallets/settlement/src/benchmarking.rs
- pallets/settlement/src/lib.rs
- pallets/weights/src/pallet_settlement.rs
- Fix weight for `reschedule_instruction`.
> MESH-1691 -  fix settlement reschedule_instruction benchmark and weight.

- pallets/staking/src/lib.rs
- pallets/staking/src/offchain_election.rs
Backports fix from:
https://github.com/PolymathNetwork/Polymesh/pull/992
into 3.3
> Fix Phragman Issue

- pallets/runtime/tests/src/compliance_manager_test.rs
Use `Scope::Ticker` in compliance manager tests.
> MESH-1704 fix scope in compliance manager tests.

- pallets/committee/src/benchmarking.rs
- pallets/pips/src/benchmarking.rs
- pallets/settlement/src/benchmarking.rs
- pallets/settlement/src/lib.rs
Fixes benchmarks - pips, settlement & committee
> MESH-1653: Some benchmark fixes

- pallets/runtime/ci/src/runtime.rs
- pallets/runtime/develop/src/runtime.rs
- pallets/runtime/itn/src/runtime.rs
- pallets/runtime/testnet/src/runtime.rs
Updates all networks to spec_version 3000, tx_version 1
> Update spec & tx version

- pallets/identity/src/keys.rs
Prompted by answering a question re. DID creation.
> Clarify DID creation

- pallets/pips/src/lib.rs
- pallets/runtime/tests/src/lib.rs
- pallets/runtime/tests/src/pips_test.rs
- Fixed behavior of `ActivePipCount` when rescheduling.
> GTN-2172: Fix behavior of `ActivePipCount` when rescheduling

- pallets/corporate-actions/src/distribution/mod.rs
This PR introduces minor doc tweaks
> docs: add missing error to distribute extrinsic

- polymesh_schema.json
Small fix to Pips RPC interface.
> Use PipId in pips RPC interface.

- pallets/runtime/ci/src/runtime.rs
- pallets/runtime/develop/src/runtime.rs
- pallets/runtime/mainnet/src/runtime.rs
- pallets/runtime/testnet/src/runtime.rs
- bumps `spec_version` to 3001
- bumps `transaction_version` to 2
> Update versions (spec & transaction)

- errors_schema.json
Improve error decoding by adding enums for module errors to the schema.
- Add generated error types to `errors_schema.json` for improved error decoding.
> Add error types to schema.

- .github/workflows/docs.yml
The github action to build Polymesh docs was broken.
> Fix docs build.

- scripts/cli/package.json
- scripts/cli/src/helpers/rewards_helper.ts
- scripts/cli/src/helpers/staking_helper.ts
- scripts/cli/src/tests/15_itn_rewards.ts
- scripts/cli/src/tests/15_portfolio.ts
- scripts/cli/src/tests/17_itn_rewards.ts
- scripts/cli/src/types.ts
Modifying ITN Rewards JS integration test.
> MESH 1654/ITN Rewards JS Test

- Cargo.lock
- Cargo.toml
- README.md
- pallets/bridge/src/lib.rs
- pallets/common/src/traits/compliance_manager.rs
- pallets/compliance-manager/src/benchmarking.rs
- pallets/compliance-manager/src/lib.rs
- pallets/relayer/src/lib.rs
- pallets/runtime/ci/src/runtime.rs
- pallets/runtime/develop/src/runtime.rs
- pallets/runtime/mainnet/src/runtime.rs
- pallets/runtime/testnet/src/runtime.rs
- pallets/weights/src/pallet_compliance_manager.rs
- primitives/src/compliance_manager.rs
- primitives/src/condition.rs
- src/chain_spec.rs
[ignore branch name - testnet_v4.0.1 should be testnet_v4.1.1]
Bump version v4.1.1 and spec: 3010
Update telemetry to use polymesh.network
- Add missing check to `relayer.accept_paying_key`.
- Add missing weight to `change_bridge_exempted`.
- Use a cost function for `Condition` type for more accurate call weights.
> Testnet v4.1.1

- polymesh_schema.json
- scripts/cli/package-lock.json
- scripts/cli/package.json
Bump the Polkadot js versions to fix a schema issue.
> Bump polkadot versions to fix schema issue.

- Cargo.lock
- Cargo.toml
- pallets/runtime/ci/src/runtime.rs
- pallets/runtime/develop/src/runtime.rs
- pallets/runtime/mainnet/src/runtime.rs
- pallets/runtime/testnet/src/runtime.rs
> New spec version format and bump major version.

- pallets/multisig/src/lib.rs
- pallets/runtime/tests/src/multisig.rs
- Created more specific error types for improving singer already linked type errors
> MESH-1792/ improving signer already linked errors
