polymesh_schema.json, primitives/src/identity_id.rs, runtime/src/identity.rs, runtime/src/test/identity.rs
The UI testing method is explained [below](https://github.com/PolymathNetwork/Polymesh/pull/156#issuecomment-574650396).
=> MESH-540: Addition of batches of claims in a single transaction

runtime/src/asset.rs
In the implementation, the asset name is essentially the token name. The ticker name still cannot be modified and remains immutable after the creation of the token. Only the token name can be changed. If you think either ticker names or something else needs to become mutable, let me know!
=> MESH-567: Modify asset name

primitives/src/identity_id.rs, runtime/src/asset.rs, runtime/src/constants.rs, runtime/src/identity.rs
Note: The original plan included a special function that allows the owner of an asset to add claim issuers to the identity of the asset. However, since the requirement of being a claim issuer for issuing claims is being dropped, we no longer need it.
This, in combination with general linked data PR, can be used to make add documents to an asset in an iterateable way.
=> Mesh 532/DID for Assets

polymesh_schema.json, runtime/src/asset.rs, runtime/src/batch_dispatch_info.rs, runtime/src/general_tm.rs, runtime/src/group.rs, runtime/src/identity.rs, runtime/src/lib.rs, runtime/src/mips.rs, runtime/src/test/identity.rs, scripts/cli/index.js
@JMoore96 
There are some changes related to *Remove claim issuer* task.
The important points here are:
- New event at `identity.rs`:  `SignerJoinedToIdentityApproved( Signer, IdentityId)`. It will be thrown one Signing key approves the request to be added to an identity.
-  In  `scripts/cli/index.js`:
- Add Claim Issuer is not needed.
- New `authorizeJoinToIdentities` function in which we wait for `SignerJoinedToIdentityApproved` event
=> Mesh 558/remove claim issuer and scripts

runtime/src/asset.rs
The following are the acceptance criteria. Please check if I implemented them OK.
=> MESH-572: capture the funding round of a token

runtime/src/asset.rs, runtime/src/test/asset_test.rs
Note that controller transfers are still [allowed](https://github.com/PolymathNetwork/Polymesh/blob/cecd1c48ee862df7224ac280ae924cf5f0790d4c/runtime/src/asset.rs#L519) but I can disallow those if you think there should be no exceptions.
=> MESH-579: freezing and unfreezing of minting and transfers

custom/staking/src/lib.rs, custom/transaction-payment/src/lib.rs, polymesh_schema.json, primitives/src/account_key.rs, primitives/src/identity.rs, primitives/src/lib.rs, primitives/src/signing_item.rs, primitives/src/traits.rs, runtime/src/asset.rs, runtime/src/balances.rs, runtime/src/committee.rs, runtime/src/contracts_wrapper.rs, runtime/src/dividend.rs, runtime/src/exemption.rs, runtime/src/general_tm.rs, runtime/src/identity.rs, runtime/src/lib.rs, runtime/src/mips.rs, runtime/src/multisig.rs, runtime/src/percentage_tm.rs, runtime/src/runtime.rs, runtime/src/simple_token.rs, runtime/src/sto_capped.rs, runtime/src/test/identity_test.rs, runtime/src/test/multisig.rs, runtime/src/test/storage.rs, runtime/src/update_did_signed_extension.rs, runtime/src/voting.rs, src/chain_spec.rs
`STOCapped`, `MIPS`, `ReferendumInfo`, `Key` and `Votes` renamed
=> Mesh 640/rename conflicting modules and types

custom/staking/src/lib.rs, runtime/src/balances.rs, runtime/src/constants.rs, runtime/src/group.rs, runtime/src/runtime.rs, src/chain_spec.rs
There's a fixed BRR address. Anyone can send funds to it. Whenever a mint is supposed to happen, the balances module checks if BRR has funds and if it has, it transfers funds away from BRR rather than minting. If BRR is out of funds, normal mint happens.
There's another change in the PR: I have reduced block time to 1 second and epoch to 60 blocks (1 min) and era to 2 epochs (120 blocks or 2 min). I did this because I wanted to quickly test the PR but didn't revert these because I don't see any downside of having a more responsive internal testnet. When we do the fee analysis, we should revert to the default/mainnet values though.
I have also adjusted some chain spec params.
=> Mesh 609/subsidize block rewards

.circleci/config.yml
To reduce cache misses, I've changed our CircleCI logic to:
1) Try and restore cache created against exactly the same lock files of all our packages
2) If that's not available (let's say we changed just the identity module), then rather than not restoring any cache, we restore the cache created for the exact lock file for the main package.
3) If that's not available, restore the cache created for the current rust version. This way, at least we won't have to rebuild the third party dependencies that haven't changed.
Other changes:
- The Rust version is also stored in the cache keys. This way, we won't be trying to restore cross rust version caches and wasting time.
- minor improvements and bug fixes :)
=> Improve circleci caching

pallets/common/src/traits/balances.rs, pallets/runtime/src/simple_token.rs, pallets/runtime/src/test/asset_test.rs, pallets/runtime/src/test/balances_test.rs
It just removes `Subtrait` in Balances.
It is not needed because we previously removed the `ElevateTrait` trick.
=> Remove unused `Subtrait`

pallets/identity/src/lib.rs, pallets/runtime/src/asset.rs, pallets/runtime/src/multisig.rs, pallets/runtime/src/test/asset_test.rs, pallets/runtime/src/test/identity_test.rs, pallets/runtime/src/test/multisig.rs, polymesh_schema.json, primitives/src/authorization.rs, primitives/src/lib.rs, primitives/src/link.rs
Authorizations and links now use double_map. That allows us to not store next and previous links and still be able to iterate over them.
In polkadot.js, `entries` function will fetch all auths/links
Example: `api.query.identity.authorizations.entries(alice)` will fetch all authorizations that alice has.
Also added ability to fetch auths given by a particular user.
=> Refactored authorizations and links

pallets/identity/src/lib.rs, pallets/runtime/src/asset.rs, pallets/runtime/src/committee.rs, pallets/runtime/src/contracts_wrapper.rs, pallets/runtime/src/dividend.rs, pallets/runtime/src/exemption.rs, pallets/runtime/src/general_tm.rs, pallets/runtime/src/percentage_tm.rs, pallets/runtime/src/simple_token.rs, pallets/runtime/src/sto_capped.rs, pallets/runtime/src/test/asset_test.rs, pallets/runtime/src/test/identity_test.rs, pallets/runtime/src/test/statistics_test.rs, pallets/runtime/src/update_did_signed_extension.rs, pallets/runtime/src/voting.rs
**Description**
In this PR we are replacing `did: IdentityId` parameter in each module function by the new call `current_identity_or` (from MESH-542).
=> Mesh 598/remove did parameter

pallets/identity/src/lib.rs
Fixed the error message returned when someone tries to create an identity with a master key that is already linked to another identity.
=> Fixed an error message

pallets/runtime/develop/src/constants.rs, pallets/runtime/develop/src/runtime.rs, pallets/staking/src/lib.rs, pallets/staking/src/mock.rs, pallets/staking/src/tests.rs, scripts/cli/environment.config.js, src/chain_spec.rs
- ensure that validators are removed if they lose their CDD status
- correctly set validator preferences on genesis and fail on errors
- remove GC functions to set compliance, and instead refresh each era
- use local rather than live for cli setup
=> Staking fixes

polymesh_schema.json
polkadot.js can't handle optional parameters anywhere else
=> fix: have optional RPC parameters at the end

pallets/balances/src/lib.rs, pallets/runtime/common/tests/all/balances_test.rs
This fixes the problem with 0-value transfer event spam but not the fact that only the treasury gets their share (80%) and the block author (the "5C" address) doesn't get anything. In other words, it was sent 0 amounts, which was causing the events to be sent.
I'm not sure at the moment why the author is neither of the stash block author accounts but rather some other fixed account.
=> MESH-973: avoid 0-value transfers

pallets/asset/src/lib.rs, pallets/common/src/protocol_fee.rs, pallets/identity/src/lib.rs, pallets/runtime/common/tests/all/ext_builder.rs, polymesh_schema.json
Rename protocol ops to pattern: `{ModuleName}{ExtrinsicName}`.
=> Rename protocol Ops

Cargo.lock, Cargo.toml, pallets/asset/Cargo.toml, pallets/asset/src/lib.rs, pallets/balances/Cargo.toml, pallets/common/Cargo.toml, pallets/common/src/traits/balances.rs, pallets/pips/Cargo.toml, pallets/pips/src/lib.rs, pallets/runtime/common/Cargo.toml, pallets/runtime/common/src/voting.rs, primitives/Cargo.toml, primitives/src/document.rs, primitives/src/identity_claim.rs, primitives/src/ignored_case_string.rs, primitives/src/lib.rs, primitives/src/smart_extension.rs, primitives_derive/Cargo.toml, primitives_derive/src/lib.rs
- New module for *procedural macros*: `primitives_derive`.
- New `derive` macros:
- `VecU8StrongTyped`: It generates code for types like `struct StrongTypeXXX( Vec<u8>)`.
- `SliceU8StrongTyped`: It generates code for types like `struct StrongTypeYYY( [u8; ZZ])`.
@vkomenda y UT has been added to `primitives` crate because we cannot test *procedural macros* in the same crate that they are defined.
=> Strong Typing added

pallets/balances/src/lib.rs, pallets/common/src/constants.rs, pallets/common/src/lib.rs, pallets/identity/src/lib.rs
- Common way to initialize Systematic Account, see `Identity::add_extra_genesis`.
- BRR and Treasury identities have a CDD claim from Systematic CDD providers (like CDD trusted provider members).
- BRR is now a real account with Id & CDD claim.
=> Common Systematic Accounts

pallets/runtime/develop/src/fee_details.rs, pallets/runtime/develop/src/runtime.rs, pallets/runtime/testnet-v1/src/fee_details.rs, pallets/runtime/testnet-v1/src/runtime.rs
This is a temporary change to have keys joining identities pay their transaction fee from the master key of the receiving identity (as opposed to the receiving identity).
This allows the Polymesh Wallet to function without needing explicit identity top up functionality.
=> Pay with master key

pallets/pips/src/lib.rs
- Implements Mesh 1119 by splitting `ProposalAmended` into `ProposalDetailsAmended` & `ProposalBondAdjusted` (+ adding url & description). (First commit)
- Throws in some code refactoring (Second commit)
=> Mesh 1119: Split `ProposalAmended` in two + code deduping

pallets/runtime/tests/src/asset_test.rs, pallets/runtime/tests/src/balances_test.rs, pallets/runtime/tests/src/bridge.rs, pallets/runtime/tests/src/ext_builder.rs, pallets/runtime/tests/src/identity_test.rs, pallets/runtime/tests/src/pips_test.rs, pallets/runtime/tests/src/transaction_payment_test.rs, pallets/runtime/tests/src/treasury_test.rs
Based on https://github.com/PolymathNetwork/Polymesh/pull/493 (first commit).
- Resolves MESH 1129: `transaction_payment_test` now uses `TestStorage` and `ExtBuilder`.
- Some other drive-by cleanup of unused imports.
=> mesh-1129: Use `TestStorage` & `ExtBuilder` for `transaction_payment_test`

pallets/committee/src/lib.rs, pallets/common/src/traits/group.rs, pallets/group/src/lib.rs, pallets/runtime/develop/src/runtime.rs, pallets/runtime/testnet-v1/src/runtime.rs, pallets/runtime/tests/src/ext_builder.rs, pallets/runtime/tests/src/group_test.rs, pallets/runtime/tests/src/staking/mock.rs, pallets/runtime/tests/src/storage.rs, src/chain_spec.rs
Add a limit of how many concurrent active members a group can have, defined and configured per group:
```rust
/// Limit of how many "active" members there can be.
pub ActiveMembersLimit get(fn active_members_limit) config(): u32;
```
This is then checked upon potentially group-adding operations (`add_member`, `reset_members`) and an error is thrown on `>` the limit.
The limit is configurable via:
```rust
pub fn set_active_members_limit(origin, limit: MemberCount);
```
which can be called by a newly added `type LimitOrigin` (so that e.g., the technical committee cannot change this themselves).
The choice of a per-group limit provides flexibility, while also seemingly being necessary for the CDD group.
=> MESH-1213: Add active members limit

pallets/pips/src/lib.rs, pallets/runtime/tests/src/pips_test.rs, polymesh_schema.json
- MESH-1238: Add `(meta: SnapshotMetadata<_>).id: u32`  for UI convenience.
- MESH-1239: Move `proposer` & `cool_off_until` from `PipsMetadata` into `Pips`.
- MESH-1240: Cache committee `PipId`s in `CommitteePips get(fn committee_pips): Vec<PipId>`.
- Schema changes/fixes overlooked in previous PRs.
=> MESH-1240, MESH-1239, MESH-1238

pallets/identity/src/lib.rs, pallets/runtime/develop/src/fee_details.rs, pallets/runtime/testnet/src/fee_details.rs
Instead of adding a new extrinsic, we alter the payer of `remove_authorization` in some cases.
=> MESH-1236: `remove_authorization` payer => `authorized_by` (sometimes)

pallets/pips/src/lib.rs, pallets/runtime/tests/src/pips_test.rs, polymesh_schema.json
- MESH-1253: Add `created_at: BlockNumber` to `PipsMetadata`
- MESH-1252: Add `SnapshotId` to `SnapshotResultsEnacted`
As requested by @pabloruiz55.
=> MESH-1252 & MESH-1253

pallets/identity/src/lib.rs, primitives/src/migrate.rs
This could be made more efficient by e.g., avoiding the decoding of `V`.
I've implemented the simpler idea for now though.
If we constrain `H` to `Blake2_128Concat` in a different function, then `_, _, _, _, _` will not be needed.
=> MESH-1243: add `migrate::migrate_double_map_keys`

pallets/pips/src/lib.rs, pallets/runtime/tests/src/committee_test.rs, pallets/runtime/tests/src/pips_test.rs, pallets/runtime/tests/src/staking/mod.rs, pallets/runtime/tests/src/storage.rs, scripts/cli/tests/11_governance_management.js
Also tightens various pips and committee tests to work with committee majority origins instead of faking it with `root()`.
=> MESH-1262: Infer `Proposer<_>` from `origin` on `Pips::propose`.

polymesh_schema.json
Defined as:
```rust
pub struct Vote<Balance>(
/// `true` if there's agreement.
pub bool,
/// How strongly do they feel about it?
pub Balance,
);
```
=> Schema: fix `Vote`'s definition due to changes

pallets/asset/src/lib.rs, pallets/common/src/traits/asset.rs, pallets/confidential-asset/src/lib.rs, pallets/runtime/tests/src/asset_test.rs, pallets/runtime/tests/src/basic_sto_test.rs, pallets/runtime/tests/src/compliance_manager_test.rs, pallets/runtime/tests/src/confidential_asset_test.rs, pallets/runtime/tests/src/confidential_test.rs, pallets/runtime/tests/src/dividend_test.rs, pallets/runtime/tests/src/ext_builder.rs, pallets/runtime/tests/src/portfolio.rs, pallets/runtime/tests/src/settlement_test.rs, pallets/runtime/tests/src/statistics_test.rs, pallets/runtime/tests/src/storage.rs, pallets/runtime/tests/src/voting_test.rs, primitives/src/asset.rs, primitives/src/lib.rs, src/chain_spec.rs
Addresses CRYP-153. Adds an extrinsic to register a confidential asset.
=> Add support for creating confidential assets.

polymesh_schema.json
Forgot to update the schema when the types changed during the PR.
=> MESH-1281: Fix `expiry` type in schema (Pips & Committee votes)

Cargo.lock, pallets/confidential/Cargo.toml, pallets/identity/Cargo.toml, pallets/runtime/tests/Cargo.toml, pallets/runtime/tests/src/confidential_test.rs, pallets/runtime/tests/src/storage.rs, polymesh_schema.json, primitives/Cargo.toml, primitives/src/investor_zkproof_data.rs, primitives/src/valid_proof_of_investor.rs
- use `develop` branch from cryptography repo
- pass bytes to confidential identity library rather than scalars
- generalise proof scopes
- fix for claim type schema
=> Move to `develop` cryptography branch, and generalise scopes

Cargo.lock, pallets/balances/src/lib.rs, pallets/committee/src/lib.rs, pallets/common/src/traits/balances.rs, pallets/common/src/traits/group.rs, pallets/common/src/traits/pip.rs, pallets/group/src/lib.rs, pallets/pips/Cargo.toml, pallets/pips/src/lib.rs, pallets/runtime/develop/src/lib.rs, pallets/runtime/develop/src/runtime.rs, pallets/runtime/testnet/src/runtime.rs, pallets/runtime/tests/src/committee_test.rs, pallets/runtime/tests/src/ext_builder.rs, pallets/runtime/tests/src/group_test.rs, pallets/runtime/tests/src/pips_test.rs, pallets/runtime/tests/src/portfolio.rs, pallets/runtime/tests/src/staking/mock.rs, pallets/runtime/tests/src/staking/mod.rs, pallets/runtime/tests/src/storage.rs, pallets/staking/src/lib.rs, polymesh_schema.json, rpc/runtime-api/src/pips.rs, scripts/cli/tests/11_governance_management.js, src/chain_spec.rs
- reverts the `tooling` branch to governance V1
- previous `tooling` branch is now at `tooling_v2.2.0`
=> Remove governance v2 from tooling branch

Cargo.lock, pallets/asset/src/lib.rs, pallets/basic-sto/src/lib.rs, pallets/common/src/traits/asset.rs, pallets/compliance-manager/src/lib.rs, pallets/runtime/develop/src/runtime.rs, pallets/runtime/testnet/src/runtime.rs, pallets/runtime/tests/src/compliance_manager_test.rs, polymesh_schema.json, rpc/runtime-api/src/compliance_manager.rs, rpc/src/compliance_manager.rs
The RPC no longer requires the user to input the PIA address. It is fetched from the asset module directly.
=> Simplify compliance_canTransfer RPC

pallets/asset/src/lib.rs, pallets/corporate-actions/src/lib.rs, pallets/identity/src/lib.rs, pallets/runtime/tests/src/asset_test.rs, pallets/runtime/tests/src/corporate_actions_test.rs, pallets/staking/src/lib.rs, pallets/weights/src/pallet_corporate_actions.rs, polymesh_schema.json, primitives/src/document.rs, primitives/src/lib.rs, primitives/src/migrate.rs, primitives_derive/src/migrate.rs
- `DocumentName` as a key is moved towards `DocumentId`.
- Also some misc refactoring.
=> MESH-1270: Link Documentation to Corporate Actions

pallets/common/src/lib.rs, pallets/identity/src/lib.rs, primitives/src/identity_id.rs
Bitmasking is no longer required since the scalar conversions are now handled by the cryptography library.
=> Removed bitmasking from IdentityId

pallets/asset/src/lib.rs, pallets/common/src/constants.rs, pallets/compliance-manager/src/lib.rs, pallets/identity/src/lib.rs, pallets/runtime/tests/src/compliance_manager_test.rs, pallets/runtime/tests/src/confidential_test.rs, polymesh_schema.json, primitives/src/condition.rs, primitives/src/proposition/mod.rs
- Moved implicit requirement (scope / Investor uniqueness claim) check from Compliance manager to Asset/Identity module.
- `AssetComplianceResult` now respects compliance pause/unpause status.
This PR is tagged as API breaking because it changes the `canTransfer` RPC
We used to return the implicit requirement check as a dedicated boolean in compliance manager's `canTransfer` RPC but we no longer do that. Instead, it's now one of the error codes returned by the asset module's `canTransfer` RPC
=> Mesh 1335/Implicit requirement should not be paused

pallets/identity/src/lib.rs, primitives/src/identity.rs, primitives/src/lib.rs
No runtime upgrade is needed because we are already clearing the DidRecords on upgrade.
=> MESH-1341/Remove IdentityRole

Cargo.lock, pallets/protocol-fee/Cargo.toml, pallets/protocol-fee/src/benchmarking.rs, pallets/protocol-fee/src/lib.rs, pallets/runtime/develop/Cargo.toml, pallets/runtime/develop/src/runtime.rs, pallets/runtime/testnet/src/runtime.rs, pallets/runtime/tests/src/staking/mock.rs, pallets/runtime/tests/src/storage.rs, pallets/weights/Cargo.toml, pallets/weights/src/lib.rs, pallets/weights/src/pallet_protocol_fee.rs
~I've auto-generated weight source files and can add them to this PR. However I think they need to be generated on the benchmark machine instead and committed separately.~
See the [comment](https://github.com/PolymathNetwork/Polymesh/pull/715#issuecomment-721729057) below.
=> MESH-1298: protocol-fee benchmarks

pallets/asset/src/lib.rs, pallets/compliance-manager/src/lib.rs, pallets/identity/src/lib.rs, primitives/src/condition.rs, primitives/src/identity_claim.rs
This PR removed runtime upgrade code which has already been executed on Alcyone 2.1.
See `alcyone` branch for storage which has already been updated.
Also fixes storage typo in:  
```
migrate_map::<Vec<TrustedIssuerOld>, _>(b"ComplianceManager", b"TrustedClaim**Isuer**", |_| Empty);
```
A companion PR will be made for the `tooling_v2.2.0` branch.
=> Remove executed runtime upgrade code

Cargo.lock, Cargo.toml, pallets/asset/Cargo.toml, pallets/basic-sto/Cargo.toml, pallets/runtime/common/src/lib.rs, pallets/runtime/develop/src/runtime.rs, pallets/runtime/testnet/src/runtime.rs, pallets/settlement/src/lib.rs, src/service.rs
There were way too many conflicts in cherry-picking the benchmarking and settlement stuff so I did manual commits from scratch. Probably easiest to review this pr commit by commit. 
The first commit enables compiled wasm.
The second commit updates the boot node identity representation.
The third commit fixes the reject instruction function in the settlement pallet.
ps. These commits contain the bare minimums. Tests, optimizations, cleanups, etc that were part of the original PRs are missing and should be merged into tolling 2.3 instead.
=> Tooling v2 patches

Cargo.lock, pallets/corporate-actions/src/ballot.rs, pallets/runtime/tests/src/corporate_actions_test.rs, pallets/runtime/tests/src/lib.rs, pallets/runtime/tests/src/storage.rs
Based on https://github.com/PolymathNetwork/Polymesh/pull/721.
Adds CA + Ballot tests per https://polymath.atlassian.net/browse/MESH-1365.
Distributions test still remain and will be added in a follow-up PR.
=> MESH-1365: Add CA + Ballot tests [Part 1]

pallets/bridge/src/lib.rs, pallets/common/src/traits/identity.rs, pallets/identity/src/lib.rs, pallets/multisig/src/lib.rs, pallets/pips/src/lib.rs, polymesh_schema.json
- Added an event in the Identity module that can be used as the global event for unexpected errors.
- Removed rustfmt skip from one place since it works fine now.
=> Mesh 1343/global error event

pallets/identity/src/benchmarking.rs, pallets/identity/src/lib.rs, pallets/runtime/develop/src/fee_details.rs, pallets/runtime/testnet/src/fee_details.rs, pallets/runtime/tests/src/fee_details.rs, pallets/runtime/tests/src/identity_test.rs
Allow caller to specify whether they should pay, or whether the issuer of the authorization should pay.
In both cases, the payer must have a valid CDD check.
=> MESH-1367: Fix `remove_authorization` logic

pallets/common/src/traits/identity.rs, pallets/identity/src/lib.rs, polymesh_schema.json, primitives/src/secondary_key.rs
- `set_permission_to_signer` function and `add_authorization` function now use the standard `Permissions` type.
- `legacy_set_permission_to_signer` function added that can be used as a workaround for https://github.com/polkadot-js/apps/issues/3632 
The main difference between the legacy type and the standard type is in the `PalletPermissions` struct. In the legacy type, we have a dedicated boolean(`total`) to represent the `None` case of an `Option` (`dispatchable_names`) but in the standard format, `dispatchable_names` is directly used as an `Option`.
=> Added LegacyPermissions as a workaround for a polkadot.js bug

pallets/identity/src/lib.rs, primitives/src/identity.rs
The issue was that we were decoding the Identity as `IdentityOld` instead of `IdentityWithRolesOld` before migrating the `IdentityWithRolesOld` to `IdentityOld`.
=> Fixed identity migration

pallets/asset/src/lib.rs, pallets/identity/src/lib.rs, pallets/staking/src/lib.rs, polymesh_schema.json
- `import` and `switch` are reserved keywords in Javascript and were creating troubles with our types generation system. This PR renames them to avoid the clash.
- Updated the errors in `set_permission_to_signer`.
- Fixed a typo in the schema.
=> Renaming and minor fixes

pallets/bridge/src/lib.rs, pallets/runtime/develop/src/fee_details.rs, pallets/runtime/testnet/src/fee_details.rs, polymesh_schema.json
This is needed to ensure the bridge relayers can batch transactions without needing to decode utility batches for the purposes of CDD checks.
=> Add batches to the bridge module

pallets/committee/src/lib.rs, pallets/runtime/tests/src/committee_test.rs
=> Committee: embed `DispatchResult` in `Executed`

pallets/pips/src/lib.rs
Now that we have upgraded Alcyone to 2.2 we only need the upgrade code to recompute the live queue.
=> Remove already executed runtime storage code

.circleci/config.yml, pallets/asset/src/lib.rs, pallets/compliance-manager/src/benchmarking.rs, pallets/compliance-manager/src/lib.rs, pallets/identity/src/lib.rs, pallets/runtime/tests/src/compliance_manager_test.rs
- `remove_default_trusted_claim_issuer` now takes only the issuer Identity instead of the full `TrustedIssuer` object. (API breaking but suggested by the SDK team)
- Investor uniqueness claim is no longer checked for the sender.
- Fixed benchmark build.
=> More minor fixes

pallets/asset/src/lib.rs, pallets/compliance-manager/src/benchmarking.rs, pallets/compliance-manager/src/lib.rs, pallets/identity/src/lib.rs, pallets/runtime/develop/src/runtime.rs, pallets/runtime/testnet/src/runtime.rs, pallets/runtime/tests/src/compliance_manager_test.rs
- Investor uniqueness claim is no longer checked for the sender.
- `remove_default_trusted_claim_issuer` now takes only the issuer Identity instead of the full `TrustedIssuer` object. (API breaking but suggested by the SDK team)
=> Backporting some minor fixes to tooling

Cargo.lock, pallets/confidential-asset/Cargo.toml, pallets/confidential-asset/src/lib.rs, pallets/confidential/Cargo.toml, pallets/confidential/src/lib.rs, pallets/identity/Cargo.toml, pallets/runtime/develop/Cargo.toml, pallets/runtime/testnet/Cargo.toml, pallets/runtime/tests/Cargo.toml, pallets/runtime/tests/src/confidential_asset_test.rs, pallets/runtime/tests/src/confidential_test.rs, pallets/runtime/tests/src/settlement_test.rs, pallets/runtime/tests/src/storage.rs, pallets/runtime/tests/src/transaction_ordering_test.rs, pallets/settlement/Cargo.toml, pallets/settlement/src/lib.rs, primitives/Cargo.toml, primitives/src/cdd_id.rs, primitives/src/investor_zkproof_data.rs, primitives/src/valid_proof_of_investor.rs
Changes to dependencies to match the restructure of cryptography repo done in https://github.com/PolymathNetwork/cryptography/pull/97
I'll fix the CI issues and then point it to the correct branch
=> Cryp 187/change mercat dependencies

Cargo.lock, pallets/asset/src/lib.rs
Adds back the IU claim check for sender & receiver of assets.
Uses `_mint` for issuance and allocation of total supply on asset creation (slightly more expensive, but less duplicated logic)
Still allows initial issuance (`create_asset` and `issue`) without IU claim.
- Both the sender and receiver of an asset settlement must have an `InvestorUniqueness` claim (previously just receiver)
- `Transfer` and `Issued` events are only emitted for `create_asset` if `total_supply > 0`
=> MESH-1416: Require IU claims for payer and receiver of transfers

Cargo.lock, pallets/runtime/tests/src/settlement_test.rs, pallets/settlement/src/benchmarking.rs, pallets/settlement/src/lib.rs, pallets/sto/src/lib.rs, polymesh_schema.json, scripts/cli/tests/12_A_settlement.js, scripts/cli/tests/12_B_settlement.js, scripts/cli/util/init.js
I haven't added runtime migration as I think it is fine for the `value_date` of previous instructions to be `None`.
- Capture `value_date` of an instruction.
- Modified `add_instruction` and `add_and_affirm_instruction` by renaming `valid_from` to `trade_date` and adding new `value_date` parameter.
- Modified `Instruction` schema.
- Modified `InstructionCreated` event.
- `value_date` of an instruction must be after `trade_date`.
=> MESH-1483: Rename valid_from to trade_date and add value_date

pallets/asset/src/lib.rs, pallets/runtime/tests/src/asset_test.rs, pallets/runtime/tests/src/compliance_manager_test.rs, pallets/runtime/tests/src/dividend_test.rs, pallets/runtime/tests/src/portfolio.rs, pallets/runtime/tests/src/settlement_test.rs, pallets/runtime/tests/src/sto_test.rs, pallets/runtime/tests/src/voting_test.rs
- A `Ticker` must now consist of ASCII characters or error `TickerNotAscii` occurs at registration or asset creation time. Not applied retroactively to existing tickers.
=> MESH-1413: ASCII-only tickers

pallets/corporate-actions/src/lib.rs, pallets/runtime/develop/src/fee_details.rs, pallets/runtime/testnet/src/fee_details.rs, polymesh_schema.json
Fixes a minor schema typo and a couple of comments.
- Schema for `CAKind` enum had a typo - `UnpredictableBenfit` should be `UnpredictableBenefit`
=> Fix minor typos

polymesh_schema.json
The underlying type is the same, UI just does more static checks on "Signature" type than a generic array type.
=> Updated schema

primitives/src/asset_identifier.rs
Asset Identifier checksums now explicitly use wrapping_* arithmetic.
=> MESH-1461/Fix underflow/overflow bugs in Asset Identifier Validations

.circleci/config.yml, Cargo.lock, Cargo.toml, pallets/committee/src/lib.rs, pallets/runtime/develop/Cargo.toml, pallets/runtime/develop/src/runtime.rs, pallets/runtime/testnet/Cargo.toml, pallets/runtime/testnet/src/runtime.rs, pallets/sudo/Cargo.toml, pallets/sudo/README.md, pallets/sudo/src/lib.rs, pallets/sudo/src/mock.rs, pallets/sudo/src/tests.rs
Release notes -
- Using a fork version of the `Sudo` pallet instead of a reference from the substrate repo.
- Fixes some weight calculation.
=> Alcyone 2.3.1 Network Upgrade

.circleci/config.yml
Executes basic benchmarks in CircleCI. The numbers from these benchmarks should not be relied upon for any final decisions.
The benchmark job takes 15 - 45 minutes with these expedited benchmarks. I think that's acceptable.
=> Execute benchmarks in CircleCI

pallets/asset/src/lib.rs, pallets/runtime/tests/src/settlement_test.rs, pallets/settlement/src/lib.rs
Added an unrelated test case, plus:
- Legs of a settlement instruction are now executed in order.
=> Execute legs in order

pallets/asset/src/lib.rs, pallets/runtime/tests/src/sto_test.rs, pallets/runtime/tests/src/storage.rs, pallets/sto/src/lib.rs
- Minimum investment amount is now checked correctly against the payment tokens instead of the offering token.
- Accounted for `price_divisor` when checking for max price.
- No longer checks that the sender is an asset holder since 0 amount transfers are allowed.
=> Fixed minor bugs in sto

pallets/asset/src/checkpoint.rs, pallets/corporate-actions/src/lib.rs, pallets/runtime/tests/src/asset_test.rs, pallets/runtime/tests/src/corporate_actions_test.rs, polymesh_schema.json, primitives/src/migrate.rs
- `ScheduleSpec` now takes `remaining` which denotes the number of CPs that can be made before the schedule expires. `remaining == 0` means the schedule will never expire. The movement from `remaining: 1 -> 0` triggers expiry. The schema is changed for this type. `StoredSchedule` receives the same change. A schema change + storage migration follows suit.
- Checkpoint schedules now store reference counts from CAs rather than removability.
As a result, `CACheckpoint::Schedule` now stores the number of CPs belonging to a schedule before attachment.
Schema changes + migration follow suit.
=> MESH-1489 (CP schedule ref counting) + MESH-1488 (CP schedule expiry-after-ticks)

.github/workflows/docs.yml
- The docs pipeline now fetches the rust version from rust-toolchain file
- The cargo doc now uses dummy wasm binaries rather than compiling proper ones. There was a race condition in binary building and wasm building otherwise.
=> Updated docs pipeline

pallets/runtime/develop/src/runtime.rs, pallets/runtime/testnet/src/runtime.rs, pallets/runtime/tests/src/staking/mock.rs, pallets/staking/src/lib.rs
Test case will be added later in a different PR. Merging this so that it can be part of the next release.
- A minimum of 1 POLYX must be locked when bonding for staking.
=> MESH-1533/Require minimum 1 POLYX bond

pallets/runtime/tests/src/staking/mock.rs, pallets/runtime/tests/src/staking/mod.rs, pallets/staking/src/lib.rs
- passing a bond amount less than `MinimumBond` to `Staking::bond` will throw a `BondTooSmall`
=> MESH-1533/add minimum bond support to staking tests

pallets/asset/src/ethereum.rs, src/chain_spec.rs, src/data/reserved_classic_tickers.json
To generate signature for claiming reserved tickers, use something like <https://app.mycrypto.com/sign-message> to sign `"classic_claim" + $did`. 
For example, Alice will sign `classic_claim0600000000000000000000000000000000000000000000000000000000000000`
- Changed how classic tickers are serialized and deserialized. It shouldn't have impact on existing networks since there was no classic ticker reserved there.
=> Mesh 713/reserve classic tickers

.circleci/config.yml
- Migrations tests were for 2.5.0 release, not applicable for next release.
- Lint check is done in Concourse as well.
=> Disabled extra CI tests

src/chain_spec.rs
- [Only applies to new networks] Address prefix changed from `5xxx` to `2xxx`. i.e. We are not using 12 as the ss58 prefix.
=> Update address prefix

pallets/asset/src/lib.rs, pallets/bridge/src/lib.rs, pallets/committee/src/lib.rs, pallets/corporate-actions/src/ballot/mod.rs, pallets/corporate-actions/src/lib.rs, pallets/identity/src/lib.rs, pallets/multisig/src/lib.rs, pallets/portfolio/src/lib.rs, pallets/runtime/tests/src/corporate_actions_test.rs, pallets/sto/src/lib.rs
Reverting changes that break storage. We will add them later with proper migrations.
Reviewers, please make sure that all changes were reverted (apart from one change in checkpoints storage since that storage has been reset anyway).
=> Revert "Mesh 1400/update storage hashers (#796)"

pallets/identity/src/benchmarking.rs, pallets/identity/src/lib.rs, pallets/utility/src/lib.rs
- No API change but a few changes in the metadata: `secondary_key::api::LegacyPermissions` -> `LegacyPermissions`, `secondary_key::api::SecondaryKey` -> `SecondaryKey`, and `<T as IdentityTrait>::OffChainSignature` -> `T::OffChainSignature`.
=> Minor refactoring

pallets/runtime/tests/src/staking/mod.rs, pallets/staking/src/lib.rs
- Fixed tracking of validators being run by an Operator. Involved storage migration to retroactively fix the `running_count`.
=> Fix validator running count

.circleci/config.yml, Cargo.lock, Cargo.toml, pallets/corporate-actions/src/benchmarking.rs, pallets/corporate-actions/src/distribution/benchmarking.rs, pallets/corporate-actions/src/distribution/mod.rs, pallets/corporate-actions/src/lib.rs, pallets/runtime/develop/src/runtime.rs, pallets/runtime/testnet/src/runtime.rs, pallets/runtime/tests/src/corporate_actions_test.rs, pallets/runtime/tests/src/staking/mod.rs, pallets/staking/src/lib.rs, polymesh_schema.json
- Type `Distribution` has gained `per_share: Balance` field. This is used instead the total supply to compute the benefit of a claimant as `per_share * shares_at_checkpoint`. (#942) 
- Fixed tracking of validators being run by an Operator. Involved storage migration to retroactively fix the `running_count`. (#946) 
- Removed error `BalanceAmountProductSupplyDivisionFailed` in Capital Distributions. (#942) 
- Renamed error `BalanceAmountProductOverflowed` to `BalancePerShareProductOverflowed` in Capital Distributions. (#942)
=> [Tooling] 2.6 Release

pallets/asset/src/lib.rs, pallets/runtime/tests/src/asset_test.rs, pallets/runtime/tests/src/corporate_actions_test.rs, pallets/runtime/tests/src/lib.rs, pallets/runtime/tests/src/storage.rs, primitives/src/asset_identifier.rs, primitives/src/smart_extension.rs
Best reviewed with whitespace changes hidden.
Also refactors asset tests as a drive-by.
- `Asset::{create_asset, update_identifiers}` now reject bad `AssetIdentifier` with the error `InvalidAssetIdentifier`.
=> Asset::{create_asset, update_identifiers} now rejects bad `AssetIdentifiers`

polymesh_schema.json, primitives/src/asset.rs
- The `AssetType` enum now has an extra variant - `StableCoin`. Schema has been updated accordingly.
=> Added stablecoins as an asset type

pallets/asset/src/lib.rs, pallets/common/src/traits/asset.rs, pallets/identity/src/lib.rs, pallets/runtime/tests/src/asset_test.rs, pallets/runtime/tests/src/identity_test.rs, pallets/runtime/tests/src/lib.rs, pallets/runtime/tests/src/staking/mock.rs, pallets/runtime/tests/src/storage.rs, primitives/src/cdd_id.rs
- Calling the `add_investor_uniqueness_claim` extrinsic in the `identity` pallet with a new investor uniqueness `claim` that has a new `ScopeId` cleans up identity-ticker balances related to the `ScopeId` of the old investor uniqueness claim if there was one.
=> Mesh 1570/clean old scope_id

pallets/staking/src/lib.rs
- The Staking `Reward` event now also contains the Identity of the key being rewarded.
=> Added identity to staking `Reward` event

Cargo.lock
Due to conflicts in Cargo.lock, build was broken. 
Resetting the lock file fixes the issue.
=> Fixed cargo.lock

pallets/portfolio/src/lib.rs, pallets/runtime/tests/src/portfolio.rs
- Setting the portfolio custodian to the owner of the portfolio now clears the `PortfolioCustodian` mapping of the portfolio ID in question thus saving some runtime storage.
=> MESH-1602: Unset PortfolioCustodian if the new custodian is the portfolio owner

pallets/corporate-actions/src/distribution/mod.rs, pallets/runtime/tests/src/corporate_actions_test.rs
- Fixed a bug in `Distribution::{claim, push_benefit}` where `remaining` could underflow/wrap when sufficient tokens were locked but `amount` was too small.
=> transfer_benefit: fix 'remaining' underflow

pallets/identity/src/lib.rs, pallets/runtime/itn/src/runtime.rs, pallets/runtime/tests/src/identity_test.rs
- GC committee is now initialized before the GC group so that GC group can add members to the committee
- The `gc_add_cdd_claim`  function now uses `add_systematic_cdd_claims` so that GC does not need to be a CDD issuer
=> Minor GC related fixes

Cargo.toml, pallets/runtime/develop/src/runtime.rs, pallets/runtime/itn/src/runtime.rs, pallets/runtime/testnet/src/runtime.rs, pallets/staking/src/lib.rs
- Set weight for election result submission to max allowed weight for normal extrinsics.
=> Fix weight for submitting election results

pallets/identity/src/lib.rs, pallets/runtime/tests/src/identity_test.rs, primitives/src/identity.rs, primitives/src/secondary_key.rs
None
None.
- Fix bug with `PartialEq for SecondaryKey<AccountId>`
- Fix duplicate secondary key bug in `add_secondary_keys_with_authorization` and `join_identity_as_identity`.
- Fix bug with removing a secondary key.
- An `AlreadyLinked` error will be thrown if a secondary key already exists.
=> MESH-1628/issue with duplicate secondary keys

pallets/asset/src/benchmarking.rs, pallets/asset/src/lib.rs, pallets/common/src/traits/asset.rs, pallets/corporate-actions/src/lib.rs, pallets/runtime/tests/src/asset_test.rs, pallets/runtime/tests/src/corporate_actions_test.rs, pallets/runtime/tests/src/ext_builder.rs, pallets/weights/src/pallet_asset.rs, polymesh_schema.json, primitives/src/asset.rs, src/chain_spec.rs
- Moved field `CorporateAction.details: CADetails` into its own storage item `Details: CAId => CADetails`.
=> MESH-1625: Move out `CADetails` from `CorporateAction`

pallets/asset/src/benchmarking.rs, pallets/asset/src/lib.rs, pallets/common/src/traits/asset.rs, pallets/corporate-actions/src/lib.rs, pallets/runtime/tests/src/asset_test.rs, pallets/runtime/tests/src/corporate_actions_test.rs, pallets/runtime/tests/src/ext_builder.rs, pallets/runtime/tests/src/settlement_test.rs, pallets/settlement/src/benchmarking.rs, pallets/settlement/src/lib.rs, pallets/weights/src/pallet_asset.rs, pallets/weights/src/pallet_settlement.rs, polymesh_schema.json, primitives/src/asset.rs, src/chain_spec.rs
- Split `Settlement.update_venue` into `update_venue_type` & `update_venue_details` along with respective events.
- Removed fields `Venue.{details, instructions}`. The former improves performance and the latter crucially removes an attack vector.
- Added storage item `Settlement.details(venue_id) -> VenueDetails`.
- Added storage item `Settlement.venue_instructions(venue_id, instruction_id) -> ()`.
=> MESH-1625: Split `Venue`

pallets/bridge/src/lib.rs, pallets/runtime/tests/src/bridge.rs, pallets/runtime/tests/src/ext_builder.rs, pallets/runtime/tests/src/signed_extra.rs, pallets/runtime/tests/src/staking/mock.rs, pallets/runtime/tests/src/staking/mod.rs
- Add support for multiple freeze admin accounts to the bridge pallet.
- New extrinsics `add_freeze_admin` and `remove_freeze_admin` to `bridge` pallet.  These can only be called by the current bridge admin to add/remove freeze admins.
- New events `FreezeAdminAdded` and `FreezeAdminRemoved`.
- Bridge extrinsic `freeze` can now be called by any of the freeze admin accounts.
=> MESH-1656/bridge freezing permissions

pallets/common/src/traits/identity.rs, pallets/identity/src/benchmarking.rs, pallets/identity/src/lib.rs, pallets/identity/src/migration.rs, pallets/runtime/develop/src/fee_details.rs, pallets/runtime/itn/src/fee_details.rs, pallets/runtime/testnet/src/fee_details.rs, pallets/runtime/tests/src/identity_test.rs, polymesh_schema.json, primitives/src/authorization.rs
- Remove the `IdentityId` from `AuthorizationData::RotatePrimaryKey`.  Use the `authorized_by` identity in `Authorization` instead.
- Use the `authorized_by` identity in `Authorization` instead of storing it in the authorization data.  This fixes an issue where anyone could rotate the pirmary key of an identity.
=> Fix pk rotation

.github/workflows/docs.yml
This adds a step to the `docs` github job to build the docs using Rust `nightly-2021-05-19`.  Which fixes an issue with the list of crates in the sidebar.
=> Use nightly 2021-05-19 for building the docs.

pallets/utility/src/lib.rs
Fix the `is_root` check in `utility.batch` extrinsic.
We are not using a `BaseCallFilter` right now, so I don't think this bug has any security issues.
=> Fix is_root check.

pallets/runtime/tests/src/settlement_test.rs, pallets/settlement/src/benchmarking.rs, pallets/settlement/src/lib.rs, pallets/weights/src/pallet_settlement.rs
- `reject_instruction` now checks that the caller is a party of at least one of the legs.  If the caller is not a party of the instruction, then `UnauthorizedSigner` error is returned.
- `reject_instruction` requires that the sender is the owner/custodian of a portfolio from at least one leg.
=> MESH-1693 - Fix reject_instruction permissions.

scripts/cli/src/tests/11_A_settlement.ts, scripts/cli/src/tests/11_B_settlement.ts, scripts/cli/src/util/init.ts
Instead of used a fixed sleep time, wait for x blocks to be produced.
=> Add a `waitBocks` utility function for the integration tests.

pallets/asset/src/lib.rs, pallets/corporate-actions/src/distribution/mod.rs, pallets/runtime/tests/src/corporate_actions_test.rs
- `CapitalDistribution.{claim, push_benefit}` will now round down for indivisible currencies before transferring gains.
=> MESH-1695: Round down in `transfer_benefit`

pallets/bridge/src/genesis.rs, pallets/common/src/benchs/mod.rs, pallets/common/src/traits/identity.rs, pallets/group/src/lib.rs, pallets/identity/src/benchmarking.rs, pallets/identity/src/lib.rs, pallets/multisig/src/lib.rs, pallets/permissions/src/lib.rs, pallets/runtime/tests/src/asset_test.rs, pallets/runtime/tests/src/identity_test.rs, pallets/runtime/tests/src/storage.rs, pallets/runtime/tests/src/utility_test.rs, pallets/staking/src/lib.rs, pallets/weights/src/pallet_identity.rs, scripts/cli/src/interfaces/augment-api-errors.ts, scripts/cli/src/interfaces/augment-api-events.ts
- Do not check permissions in `Identity::leave_identity_as_key`.
- Removed extrinsics `Identity::{join, leave}_identity_as_identity` and `Identity::revoke_offchain_authorization`.
- Removed event `Identity.ForwardedCall`.
- Removed errors `{Permissions, Identity}.RecursionNotAllowed`
=> MESH-1675: Don't check perms in `Identity::leave_identity_as_key` + Remove some extrinsics

pallets/asset/src/checkpoint/mod.rs, pallets/asset/src/lib.rs, pallets/common/src/protocol_fee.rs, pallets/corporate-actions/src/ballot/mod.rs, pallets/corporate-actions/src/distribution/mod.rs, pallets/runtime/tests/src/ext_builder.rs, pallets/runtime/tests/src/identity_test.rs, pallets/test-utils/src/lib.rs, polymesh_schema.json, src/chain_spec.rs
ProtocolOp fees updated to:
```
"AssetRegisterTicker",
"AssetIssue",
"AssetAddDocuments",
"AssetCreateAsset",
"CheckpointCreateSchedule",
"ComplianceManagerAddComplianceRequirement",
"IdentityCddRegisterDid",
"IdentityAddClaim",
"IdentityAddSecondaryKeysWithAuthorization",
"PipsPropose",
"ContractsPutCode",
"CorporateBallotAttachBallot",
"CapitalDistributionDistribute"
```
Also updates protocol ID from polymath to polymesh
=> MESH-1706: Update protocol fees

pallets/multisig/src/lib.rs, pallets/staking/src/lib.rs, polymesh_schema.json, src/chain_spec.rs
Revert RPC changes from https://github.com/PolymathNetwork/Polymesh/pull/1136 as they cause issues with the SDK.
We will revisit these, and leave these changes in our forks of polkadot.js for now.
=> Revert RPC schema changes

pallets/asset/src/lib.rs, pallets/common/src/traits/asset.rs, pallets/identity/src/claims.rs, pallets/runtime/tests/src/staking/mock.rs, pallets/runtime/tests/src/statistics_test.rs, pallets/runtime/tests/src/storage.rs
Minting of new tokens wasn't updating the scope balance for the issuer if Investor Uniqueness was disabled.
- New event `asset.InvestorUniquenessClaimNotAllowed` - This is thrown if an issuer tries to add an investor uniqueness claim for a ticker that has uniqueness disabled.
- `identity.add_investor_uniqueness_claim` and `identity.add_investor_uniqueness_claim_v2` will throw error `InvestorUniquenessClaimNotAllowed` if the ticker has IU disabled.
- `asset.issue` - Now correctly updates the scope balance.
- An InvestorUniqueness claim (both v1 and v2) is not allowed for tickers with Investor Uniqueness disabled.
=> MESH-1746 fix scope with disabled investor uniqueness

pallets/multisig/src/lib.rs, pallets/runtime/tests/src/multisig.rs
- `make_multisig_signer` - Use empty permissions when adding a multisig as a secondary key.
- `create_or_approve_proposal_as_identity`, `create_proposal_as_identity`, `approve_as_identity`, `reject_as_identity`, `accept_multisig_signer_as_identity` - Add call permissions checks to make sure that secondary keys for the identity have the right permissions.
=> MESH-1748 improve default mutisig permissions

pallets/common/src/traits/identity.rs, pallets/identity/src/auth.rs, pallets/identity/src/benchmarking.rs, pallets/identity/src/keys.rs, pallets/identity/src/lib.rs, pallets/multisig/src/lib.rs, pallets/runtime/ci/src/fee_details.rs, pallets/runtime/common/src/fee_details.rs, pallets/runtime/develop/src/fee_details.rs, pallets/runtime/mainnet/src/fee_details.rs, pallets/runtime/testnet/src/fee_details.rs, pallets/runtime/tests/src/identity_test.rs, pallets/weights/src/pallet_identity.rs, polymesh_schema.json, primitives/src/authorization.rs
- Added new extrinsic `rotate_primary_key_to_secondary`.
- Added new extrinsic `rotate_primary_key_to_secondary`.
- Added new Item to enum `AuthorizationData::RotatePrimaryKeyToSecondary(Permissions)`.
- Added new Item to enum `AuthorizationType::RotatePrimaryKeyToSecondary`.
- `accept_primary_key` now accepts secondary keys as the new primary key.
=> MESH-1743 Add rotate_primary_key extrinsic

pallets/runtime/common/src/runtime.rs, pallets/runtime/tests/src/staking/mock.rs, pallets/runtime/tests/src/staking/mod.rs, pallets/staking/src/inflation.rs, pallets/staking/src/lib.rs, pallets/staking/src/offchain_election.rs, pallets/staking/src/rustfmt.toml, pallets/staking/src/slashing.rs, pallets/staking/src/weights.rs
- Make sure to review with whitespace changes hidden and focus on the perf/semantic changes.
- Many changes here are aimed at minimizing the diff to the [tag `v3.0.0` in substrate](https://github.com/paritytech/substrate/blob/v3.0.0/frame/staking/src/lib.rs) which is really the ultimate goal of this PR.
- `Staking.{bond_extra, rebond}` check that the new active amount >= the `minimum_balance`.
- `Staking.withdraw_unbonded` is also updated to use `minimum_balance` instead of zero.
- `Staking.reap_stash` now considers `minimum_balance` also.
- `Staking.validate` can now throw errors `StashIdentityDoesNotExist` and `StashIdentityNotPermissioned`.
- `Staking.nominate` now throws `TooManyTargets` on `targets.len() <= MAX_NOMINATIONS`. It also considers blocked validators.
=> Bring in some substrate 3.0 changes to staking

pallets/asset/src/lib.rs, pallets/runtime/tests/src/asset_test.rs
- `asset.create_asset` - Now checks if `AssetType::Custom` is valid.  Will throw error `InvalidCustomAssetTypeId` if a custom asset hasn't been registered for that type id.
=> MESH-1752 check custom asset type id

pallets/external-agents/src/lib.rs
- On `Asset.createAsset`, the event `AgentAdded` is now emitted.
=> MESH-1756: Emit `AgentAdded` on asset creation

polymesh_schema.json
Our `OffChainSignature` type in `polymesh_schema.json` was wrong.
In our runtimes we use `sp_runtime::MultiSignature` for `OffChainSignature`.  Our schema had the wrong type for variant `Ecdsa`.  A `H512` is 64 bytes long, but ecdsa signatures have an extra byte (8 bits for recovery ID):
https://github.com/PolymathNetwork/substrate/blob/1fe1f43666016d6c95743c6a81c8e5b57a3058bb/primitives/core/src/ecdsa.rs#L229
=> Small schema fix.

pallets/common/src/traits/identity.rs, pallets/identity/src/benchmarking.rs, pallets/identity/src/lib.rs, pallets/weights/src/pallet_identity.rs, primitives/src/secondary_key.rs
- Add permission complexity to the weights of extrinsics: `identity.add_authorization`, `identity.set_permission_to_signer`, `identity.legacy_set_permission_to_signer`, and `identity.add_secondary_keys_with_authorization`
=> Include permmisions complexity in extrinsic weight.

pallets/identity/src/lib.rs
Fix the order of extrinsics in the Identity pallet.
=> MESH-1778 Fix order of calls in identity pallet.

pallets/portfolio/src/lib.rs, pallets/runtime/tests/src/portfolio.rs
The portfolio name is now removed from the NameToNumber mapping in the `delete_portfolio` extrinsic.
=> MESH-1759 Remove porfolio name to number mapping after deletion

pallets/common/src/traits/compliance_manager.rs, pallets/compliance-manager/src/benchmarking.rs, pallets/compliance-manager/src/lib.rs, pallets/weights/src/pallet_compliance_manager.rs, primitives/src/compliance_manager.rs, primitives/src/condition.rs
- Use a cost function for `Condition` type for more accurate call weights.
=> MESH-1773 & MESH-1777 condition cost function

Cargo.lock, Cargo.toml, pallets/bridge/src/lib.rs, pallets/relayer/src/lib.rs, pallets/runtime/ci/src/runtime.rs, pallets/runtime/develop/src/runtime.rs, pallets/runtime/mainnet/src/runtime.rs, pallets/runtime/testnet/src/runtime.rs
Bump version v4.1.1 and spec: 3010
- Add missing check to `relayer.accept_paying_key`.
- Add missing weight to `change_bridge_exempted`.
=> MESH-1787 relayer fixes

pallets/multisig/src/lib.rs, pallets/runtime/tests/src/multisig.rs
The `multisig.create_proposal_as_*` calls where replacing/changing the proposal ids for previous proposals.
- Change `multisig.create_create_proposal_as_key` and `multisig.create_proposal_as_identity` to not use the `multsig::ProposalIds` map.
=> MESH-1794 - Fix issue with MultiSig Proposal to id map.

pallets/common/src/traits/identity.rs, pallets/common/src/traits/multisig.rs, pallets/identity/src/keys.rs, pallets/multisig/src/benchmarking.rs, pallets/multisig/src/lib.rs, pallets/runtime/ci/src/runtime.rs, pallets/runtime/common/src/lib.rs, pallets/runtime/develop/src/runtime.rs, pallets/runtime/mainnet/src/runtime.rs, pallets/runtime/testnet/src/runtime.rs, pallets/runtime/tests/src/identity_test.rs, pallets/runtime/tests/src/multisig.rs, pallets/runtime/tests/src/staking/mock.rs, pallets/runtime/tests/src/storage.rs, pallets/weights/src/pallet_multisig.rs, scripts/cli/src/interfaces/lookup.ts
Fix balance check when removing a MultiSig from an identity.
- Rename `multisig.make_multisig_signer` -> `multisig.make_multisig_secondary`.  The old name was confusing to users, since it adds the multisig as a secondary key to the identity that created the multisig.
- Fixed the balance check for MultiSig primary/secondary keys.
- MultiSig balance limit changed from zero to `1.0 POLYX`.
- Remove dead code `unlink_multisig_signers_from_did()`, since the signers for a multisig are never linked to the identity.
=> MESH-1793 multisig primary/secondary key with balance.

pallets/identity/src/claims.rs
- Adding secondary key and permissions length checks to `cdd_register_did`
=> MESH-1767 - Add secondary key and permissions length checks to `cdd_register_did`

pallets/identity/src/keys.rs, pallets/runtime/tests/src/lib.rs, pallets/runtime/tests/src/storage.rs, pallets/runtime/tests/src/treasury_test.rs, pallets/treasury/src/lib.rs
- Added error `Treasury::InvalidIdentity` returned from `Treasury::disbursement` if one of the beneficiaries doesn't exist or doesn't have a primary key.
- Added the primary key to event `Treasury::TreasuryDisbursement`.
- Added event `Treasury::TreasuryDisbursementFailed` event for disbursements that fail.
- `Treasury::disbursement()` now checks if the beneficiaries exist and have a primary key.
- If the treasury disbursement transfer fails (treasury balance locked, beneficiary missing CDD), then event `Treasury::TreasuryDisbursementFailed`.
- `Treasury::disbursement` emits the `Balances::Transfer` event for each disbursement beneficiary.
=> MESH-1806 verify did in treasury disbursement

Cargo.lock, Cargo.toml, node-rpc/Cargo.toml, node-rpc/src/lib.rs, pallets/contracts/src/benchmarking.rs, pallets/contracts/src/lib.rs, pallets/runtime/ci/Cargo.toml, pallets/runtime/common/src/runtime.rs, pallets/runtime/develop/Cargo.toml, pallets/runtime/mainnet/Cargo.toml, pallets/runtime/testnet/Cargo.toml, pallets/runtime/tests/Cargo.toml, pallets/runtime/tests/src/contracts_test.rs, src/service.rs
- Contracts `instantiate` APIs now use empty permissions by default.
- Enable RPC for contracts.
=> MESH-1824: Empty perms default + MESH-1825: Contracts RPC
